# Generated by Django 3.2.9 on 2021-11-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
